### ISSUE TITLE
Fork to support CKEditor's Spoiler Plugin?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/ckeditor_accordion#3]
Hi,

is it possible to fork this module to implement [CKEditor's Spoiler Plugin](https://ckeditor.com/cke4/addon/spoiler)? I tried it at https://github.com/djzwerg/ckeditor_spoiler but it doesn't work :-(.

**Comment by indigoxela** [comment]
> is it possible to fork this module to implement CKEditor's Spoiler Plugin?

Forking is always possible. It's Open Source. :wink: 

> I tried it at https://github.com/djzwerg/ckeditor_spoiler but it doesn't work :-(.

Hm. That link's a 404.

Do you want to create a new module? That's not quite the same as forking.

**Comment by djzwerg** [comment]
I thought it would be possible to change the code of this module to support the Spoiler Plugin instead of Accordion.

**Comment by indigoxela** [comment]
> I thought it would be possible to change the code of this module to support the Spoiler Plugin instead of Accordion.

You can, of course, use ckeditor_accordion as an example for your new module.

You'd have to implement hook_ckeditor_plugins() in your module and add the plugin code accordingly.

**Comment by djzwerg** [comment]
Ok, thanks. I think I don't have enough coding skills. I can't get it work :-(

**Comment by indigoxela** [comment]
> I can't get it work

Yes, a CKEditor plugin isn't the easiest to start with. Unfortunately I'm too short on time to take this over. Maybe you'll find someone in our [Zulip chat](https://backdrop.zulipchat.com/)?

**Comment by indigoxela** [comment]
Given, this issue is ancient and didn't have any feedback for a looong time, and given, CKE4 is EOL for quite a while, I'm closing this issue.
