### ISSUE TITLE
Unable to add/remove tabs

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/ckeditor_accordion#4]
I can insert an accordion but it's only two tabs. In the plugin code I see that it's supposed to add a context menu to add tabs before or after, but for me at least these are not showing.

**Comment by indigoxela** [comment]
Wow, how can this ever have worked?

@herbdool a PR is available for testing. Funny enough, the fix is a one-liner to simply load the missing plugin-dependency.

**Comment by herbdool** [comment]
Aha! Thanks @indigoxela!

I was testing your PR out for awhile and I thought it still wasn't working. Until I realized that I needed to use the other mouse button to see the context menu. This will do!

I noticed there's no official maintainer. Would you be willing to be listed as the maintainer even if it's just for merging on bug fix PRs that other people make? Otherwise, there'd be no one to make a release when needed.

**Comment by indigoxela** [comment]
> Until I realized that I needed to use the other mouse button to see the context menu

Yes, this is now (again) as it also works in the Drupal version. Maybe not ideal UX, but functional.

> I noticed there's no official maintainer.

As noted in the chat, I've never used that module, only ported it for someone else (and silently hoped, someone takes over maintenance - which, of course, never happened). It probably makes sense to make me officially maintainer. :wink:

**Comment by herbdool** [comment]
Thanks @indigoxela. At least it's a fairly simple module. Now that it's fully working shouldn't need much attention. And it's probably ready for an official release. I've tested it a bunch and I haven't found any other problems.
