### ISSUE TITLE
Setting "Collapse all tabs by default" has a wrong description

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/ckeditor_accordion#6]
The setting "Collapse all tabs by default" on the configuration page (`admin/config/content/ckeditor_accordion`) has a wrong description:

> The maximum number of links to display in the block.

According to the [D7 issue](https://www.drupal.org/project/ckeditor_accordion/issues/3024250) it seems that the description was copied from somewhere. It's however not related to the module, and I agree with the suggestion in the D7 issue to remvoe the description as the label "Collapse all tabs by default" is meaningful enough.

(PR upcoming)

**Comment by olafgrabienski** [comment]
A PR is available: https://github.com/backdrop-contrib/ckeditor_accordion/pull/7

**Comment by indigoxela** [comment]
Wow, that's a silly mistake, I never actually used the module, obviously. :laughing:

Many thanks for reporting and PR. Merge underway... :wink:
